#!/bin/bash
set -euo pipefail

NAUTOBOT_ROOT=/opt/nautobot

# ---------------------------------------------------------------------------
# PostgreSQL
# ---------------------------------------------------------------------------
echo "==> [02] Configuring PostgreSQL..."
sudo -u postgres psql -c "CREATE USER nautobot WITH PASSWORD 'nautobot';" 2>/dev/null || \
  echo "  (nautobot DB user already exists, skipping)"
sudo -u postgres psql -c "CREATE DATABASE nautobot OWNER nautobot;" 2>/dev/null || \
  echo "  (nautobot database already exists, skipping)"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE nautobot TO nautobot;"

# ---------------------------------------------------------------------------
# Nautobot configuration
# ---------------------------------------------------------------------------
echo "==> [02] Generating secret key..."
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(50))")

echo "==> [02] Creating required directories..."
mkdir -p "$NAUTOBOT_ROOT"/{git,jobs,media,static}
mkdir -p "$NAUTOBOT_ROOT/media"/{devicetype-images,image-attachments}
chown -R nautobot:nautobot "$NAUTOBOT_ROOT"/{git,jobs,media,static}

echo "==> [02] Writing nautobot_config.py..."
# NOTE: outer heredoc is UNQUOTED so ${SECRET_KEY} is expanded by bash.
#       Python does not use $, so no other expansions occur.
sudo -u nautobot tee "$NAUTOBOT_ROOT/nautobot_config.py" > /dev/null <<PYEOF
# nautobot_config.py - generated by Packer build
#
# Import Nautobot's bundled defaults first, then override specific settings.
# This ensures all required Nautobot 3.x settings exist with sensible defaults.
from nautobot.core.settings import *  # noqa: F401,F403
import os

# ---------------------------------------------------------------------------
# Nautobot root and required storage directories
# These must be set here because they are derived from NAUTOBOT_ROOT.
# ---------------------------------------------------------------------------
NAUTOBOT_ROOT = os.environ.get("NAUTOBOT_ROOT", "/opt/nautobot")

GIT_ROOT    = os.environ.get("NAUTOBOT_GIT_ROOT",    os.path.join(NAUTOBOT_ROOT, "git"))
JOBS_ROOT   = os.environ.get("NAUTOBOT_JOBS_ROOT",   os.path.join(NAUTOBOT_ROOT, "jobs"))
MEDIA_ROOT  = os.environ.get("NAUTOBOT_MEDIA_ROOT",  os.path.join(NAUTOBOT_ROOT, "media"))
STATIC_ROOT = os.environ.get("NAUTOBOT_STATIC_ROOT", os.path.join(NAUTOBOT_ROOT, "static"))

# ---------------------------------------------------------------------------
# Core Django settings
# ---------------------------------------------------------------------------
DEBUG = os.environ.get("NAUTOBOT_DEBUG", "false").lower() == "true"

# Override per-deployment via NAUTOBOT_SECRET_KEY environment variable or
# by editing this value in nautobot_config.py.
SECRET_KEY = os.environ.get("NAUTOBOT_SECRET_KEY", "${SECRET_KEY}")

# Comma-separated hostnames/IPs; "*" allows any (restrict per-host via cloud-init)
ALLOWED_HOSTS = os.environ.get("NAUTOBOT_ALLOWED_HOSTS", "*").split(",")

# ---------------------------------------------------------------------------
# Database (PostgreSQL)
# ---------------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("NAUTOBOT_DB_NAME", "nautobot"),
        "USER": os.environ.get("NAUTOBOT_DB_USER", "nautobot"),
        "PASSWORD": os.environ.get("NAUTOBOT_DB_PASSWORD", "nautobot"),
        "HOST": os.environ.get("NAUTOBOT_DB_HOST", "localhost"),
        "PORT": os.environ.get("NAUTOBOT_DB_PORT", ""),
        "CONN_MAX_AGE": int(os.environ.get("NAUTOBOT_DB_TIMEOUT", "300")),
    }
}

# ---------------------------------------------------------------------------
# Redis cache
# ---------------------------------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("NAUTOBOT_REDIS_URL", "redis://localhost:6379/1"),
        "TIMEOUT": 300,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": os.environ.get("NAUTOBOT_REDIS_PASSWORD", ""),
        },
    }
}

# ---------------------------------------------------------------------------
# Celery (background tasks / workers)
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = os.environ.get(
    "NAUTOBOT_CELERY_BROKER_URL", "redis://localhost:6379/0"
)
CELERY_RESULT_BACKEND = os.environ.get(
    "NAUTOBOT_CELERY_RESULT_BACKEND", "redis://localhost:6379/0"
)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "normal": {
            "format": "%(asctime)s %(levelname)-7s %(name)s : %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "normal",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "/var/log/nautobot/nautobot.log",
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "normal",
        },
    },
    "loggers": {
        "django": {"handlers": ["console", "file"], "level": "INFO"},
        "nautobot": {"handlers": ["console", "file"], "level": "INFO"},
    },
}
PYEOF

# ---------------------------------------------------------------------------
# Database migrations
# ---------------------------------------------------------------------------
echo "==> [02] Running database migrations..."
sudo -u nautobot bash -c \
  "NAUTOBOT_ROOT=$NAUTOBOT_ROOT $NAUTOBOT_ROOT/bin/nautobot-server migrate --no-input"

# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------
echo "==> [02] Collecting static files..."
sudo -u nautobot bash -c \
  "NAUTOBOT_ROOT=$NAUTOBOT_ROOT $NAUTOBOT_ROOT/bin/nautobot-server collectstatic --no-input"

# ---------------------------------------------------------------------------
# Default superuser
# WARNING: Change credentials immediately after first boot.
# ---------------------------------------------------------------------------
echo "==> [02] Creating default superuser (admin / admin)..."
sudo -u nautobot bash -c \
  "NAUTOBOT_ROOT=$NAUTOBOT_ROOT DJANGO_SUPERUSER_PASSWORD=admin \
   $NAUTOBOT_ROOT/bin/nautobot-server createsuperuser \
     --username admin \
     --email admin@localhost \
     --no-input" \
  || echo "  (superuser already exists or creation skipped)"

# ---------------------------------------------------------------------------
# uWSGI configuration
# ---------------------------------------------------------------------------
echo "==> [02] Writing uWSGI configuration..."
sudo -u nautobot tee "$NAUTOBOT_ROOT/uwsgi.ini" > /dev/null <<'UWSGI'
[uwsgi]
; Unix socket - Nginx communicates through this
; Socket is owned nautobot:nautobot 660; www-data can access it because
; it is added to the nautobot group (see usermod below).
socket          = /opt/nautobot/nautobot.sock
chmod-socket    = 660

; Serve static files directly (Nginx also handles /static/)
static-map      = /static=/opt/nautobot/static

; WSGI application entry point
module          = nautobot.core.wsgi:application
single-interpreter = true

; Master process is required by nautobot.core.wsgi (uwsgidecorators)
master          = true

; Worker processes (2n+1 where n = CPU cores)
processes       = 3
enable-threads  = true

; Logging
logto           = /var/log/nautobot/nautobot.log

; Reliability
vacuum          = true
die-on-term     = true
need-app        = true
UWSGI

# ---------------------------------------------------------------------------
# systemd service units
# ---------------------------------------------------------------------------
echo "==> [02] Installing systemd service units..."

cat > /etc/systemd/system/nautobot.service <<'SERVICE'
[Unit]
Description=Nautobot WSGI Service
Documentation=https://docs.nautobot.com/
After=network-online.target postgresql.service redis-server.service
Wants=network-online.target

[Service]
Type=simple
Environment="NAUTOBOT_ROOT=/opt/nautobot"
User=nautobot
Group=nautobot
PIDFile=/var/tmp/nautobot.pid
WorkingDirectory=/opt/nautobot
ExecStart=/opt/nautobot/bin/nautobot-server start \
    --pidfile /var/tmp/nautobot.pid \
    --ini /opt/nautobot/uwsgi.ini
KillSignal=SIGINT
Restart=on-failure
RestartSec=30
PrivateTmp=true

[Install]
WantedBy=multi-user.target
SERVICE

cat > /etc/systemd/system/nautobot-worker.service <<'SERVICE'
[Unit]
Description=Nautobot Celery Worker
Documentation=https://docs.nautobot.com/
After=network-online.target nautobot.service
Wants=network-online.target

[Service]
Type=exec
Environment="NAUTOBOT_ROOT=/opt/nautobot"
User=nautobot
Group=nautobot
WorkingDirectory=/opt/nautobot
ExecStart=/opt/nautobot/bin/nautobot-server celery worker \
    --loglevel INFO \
    --logfile /var/log/nautobot/nautobot-worker.log
Restart=on-failure
RestartSec=30
PrivateTmp=true

[Install]
WantedBy=multi-user.target
SERVICE

cat > /etc/systemd/system/nautobot-scheduler.service <<'SERVICE'
[Unit]
Description=Nautobot Celery Scheduler
Documentation=https://docs.nautobot.com/
After=network-online.target nautobot.service
Wants=network-online.target

[Service]
Type=exec
Environment="NAUTOBOT_ROOT=/opt/nautobot"
User=nautobot
Group=nautobot
WorkingDirectory=/opt/nautobot
ExecStart=/opt/nautobot/bin/nautobot-server celery beat \
    --loglevel INFO \
    --logfile /var/log/nautobot/nautobot-scheduler.log \
    --pidfile /var/tmp/nautobot-scheduler.pid
Restart=on-failure
RestartSec=30
PrivateTmp=true

[Install]
WantedBy=multi-user.target
SERVICE

# ---------------------------------------------------------------------------
# Nginx
# ---------------------------------------------------------------------------
echo "==> [02] Configuring Nginx..."
cat > /etc/nginx/sites-available/nautobot <<'NGINX'
server {
    listen 80 default_server;
    server_name _;
    client_max_body_size 25m;

    location /static/ {
        alias /opt/nautobot/static/;
    }

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/opt/nautobot/nautobot.sock;
        uwsgi_read_timeout 120s;
        uwsgi_connect_timeout 120s;
    }
}
NGINX

ln -sf /etc/nginx/sites-available/nautobot /etc/nginx/sites-enabled/nautobot
rm -f /etc/nginx/sites-enabled/default

# Allow Nginx (www-data) to read the nautobot socket
usermod -aG nautobot www-data

# ---------------------------------------------------------------------------
# Enable all services
# ---------------------------------------------------------------------------
echo "==> [02] Enabling services..."
systemctl daemon-reload
systemctl enable nautobot nautobot-worker nautobot-scheduler

echo "==> [02] Configuration complete."
